/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.fdfis;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.List;

class LibraryTest {
    @Test
    void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    void exampleOne() {
        String[] input = { "root/a 1.txt(abcd) 2.txt(efgh)", "root/c 3.txt(abcd)", "root/c/d 4.txt(efgh)",
                "root 4.txt(efgh)", };
        List<List<String>> output = Library.findDuplicate(input);
        List<List<String>> expected = Arrays.asList(Arrays.asList("root/a/2.txt", "root/c/d/4.txt", "root/4.txt"),
                Arrays.asList("root/a/1.txt", "root/c/3.txt"));

        assertEquals(expected, output);
    }

    @Test
    void exampleTwo() {
        String[] input = { "root/a 1.txt(abcd) 2.txt(efgh)", "root/c 3.txt(abcd)", "root/c/d 4.txt(efgh)" };
        List<List<String>> output = Library.findDuplicate(input);
        List<List<String>> expected = Arrays.asList(Arrays.asList("root/a/2.txt", "root/c/d/4.txt"),
                Arrays.asList("root/a/1.txt", "root/c/3.txt"));

        assertEquals(expected, output);
    }
}
