/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.mi;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class LibraryTest {
    @Test
    void exampleOne() {
        int[][] input = { { 1, 3 }, { 2, 6 }, { 8, 10 }, { 15, 18 } };
        int[][] result = Library.merge(input);
        int[][] expected = { { 1, 6 }, { 8, 10 }, { 15, 18 } };

        assertEquals(expected.length, result.length);
        for (int i = 0; i < result.length; ++i) {
            assertTrue(Arrays.equals(expected[i], result[i]));
        }
    }

    @Test
    void exampleTwo() {
        int[][] input = { { 1, 4 }, { 4, 5 } };
        int[][] result = Library.merge(input);
        int[][] expected = { { 1, 5 } };

        assertEquals(expected.length, result.length);
        for (int i = 0; i < result.length; ++i) {
            assertTrue(Arrays.equals(expected[i], result[i]));
        }
    }
}
