[package]
name = "reorder-data-in-log-files"
version = "0.1.0"
authors = ["Michael Kennedy <michaeljkennedy@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
